name: 'AWS Marketplace Publish'
description: 'Publish a new version of a product in AWS Marketplace'
author: 'Luca Comellini <lucacome>'
inputs:
  product-id:
    description: 'Product ID'
    required: true
  release-notes:
    description: 'Release notes for the new version'
    required: true
  registry:
    description: 'ECR registry with tag'
    required: true
  version:
    description: 'Version of the new release'
    required: true
  description:
    description: 'Description of the new release'
    required: true
  usage-instructions:
    description: 'Usage instructions for the new release'
    required: true
  compatible-services:
    description: 'What services is this version of your product compatible with?'
    required: false
  resources:
    description: 'What resources are available for users to deploy your software?'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
